---

############################
# Default variables     #
# ##########################

rollback_flag: false

# Purge variables
rotate_file_pattern: "louvre-etor*"
rotate_file_type: .tar.gz
rotate_max_age: 5

# Fichiers à templatiser
templates_applicatifs:
  - { src: "watchdog.conf.j2", dest: "etc/watchdog.conf",  owner: "{{ app_server_user }}", group: "{{ app_name }}", mode: "0755" }
  - { src: "SHUT", dest: "{{app_server_home}}", owner: "{{ app_server_user }}", group: "{{ app_name }}", mode: "0755" }
  - { src: "START", dest: "{{app_server_home}}", owner: "{{ app_server_user }}", group: "{{ app_name }}", mode: "0755" }

  
  