---

## Deployment of deliverables

- name: "Initialisation Variables de livraison"
  set_fact:
    deploiement_sources_url_nexus: "{{ nexus_url }}/{{nexus_repo_release}}/{{artifact_id}}{{ (version | upper) }}/{{artifact_id}}-{{ (version | upper) }}{{ artifact_extension }}"
 
 # Delete the oldest backup before downloading the new one.
- name: "Purges les anciennes livraison existantes"
  include_tasks: "commun/purge_directory.yml"
  vars:
    rotate_file_folder: "{{ delivery_dir }}"
    rotate_min_count: "{{ rotate_delivery_dir }}"
    rotate_file_pattern: "*.jar"

## Component download
- name: "Telechargement livrable {{ version }}"
  maven_artifact:
    repository_url: "{{ deploiement_sources_url_nexus }}"
    group_id: "{{ artifact_groupid }}"
    artifact_id: "{{ artifact_id }}"
    version: "{{ version }}"
    classifier: "{{ artifact_classifier }}"
    extension: "{{ artifact_extension }}"
    owner: "{{ pi_user_deploy }}"
    dest: "{{ delivery_dir }}"
    username: "{{ nexus_user }}"
    password: "{{ nexus_pass }}"
    verify_checksum: always
    validate_certs: no
  register: download_info

