---
##########################################################################
# Upload Configuration files
#
##########################################################################

# Templetisation des fichier application.properties, setenv, SHUT, BOOT et STATUS
- name: "File Validation {{ item.src }}"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items: "{{ templates_applicatifs }}"

  
