---

# Creation of application directories

- name: Create application directories
  become: yes
  become_user: "{{ app_server_user }}"
  file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode }}"
    owner: "{{ item.owner|default(app_server_user) }}"
    group: "{{ item.group|default(app_server_user) }}"
  loop: "{{ louvre-etor_directory_to_create }}"
