---
#########################################
# Validation of prerequisites
#########################################

# Verification of mandatory variables
- name: "Verification des variables obligatoires"
  fail:
    msg: "'{{ item }}' doit etre definie"
  when: "
    (vars[item] is undefined)
       or
    (vars[item] is none)
       or
    (vars[item] | trim == '')
    "
  loop: "{{ applicative_required_vars | default([]) }}"

  # Creation of delivery_dir
- name: Creation delivrey_dir
  file:
    path: "{{ delivery_dir }}"
    state: directory
    owner: "{{ app_server_user }}"
    group: "{{ app_server_user }}"
    mode: "0755"

# Check Java version:
- name: "Recupere la version de Java"
  shell: java -version 2>&1 | grep version | awk '{print $3}' | sed 's/"//g'
  changed_when: false
  failed_when: javaver.rc > 0
  register: javaver

- name: "Verification de la version de Java"
  assert:
    that:
      -  "{{ javaver.stdout is version('1.8', '>=') }}"

# Check that watchdog is installed
- name: Check if watchdog config file exists and fail task if watchdog.conf file not present
  command: ls /etc/watchdog.conf
  register: result
  failed_when:
    # - result.rc == 0
    - '"No such" not in result.stdout'

# - name: Check watchdog is installed
#   apt:
#     name: watchdog
#     state: present


   
# Check weekly reboot is configured.   
- name: Ensure that a weekly reboot exists. 
  cron:
    name: "weekly reboot"
    weekday: "0"
    hour: "0"
    job: "sudo shutdown -r"

  